"""add index on original_url

Revision ID: df30729a070d
Revises: 9f4061d8f36f
Create Date: 2026-03-11 14:47:51.399149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df30729a070d'
down_revision: Union[str, Sequence[str], None] = '9f4061d8f36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_links_original_url'), 'links', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_original_url'), table_name='links')
    # ### end Alembic commands ###
