worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Rate limit: 10 запросов в секунду на IP адрес для создания ссылки
    limit_req_zone $binary_remote_addr zone=shorten_limit:10m rate=10r/s;

    upstream app {
        server app:8000;
    }

    server {
        listen 80;

        # POST /shorten - rate limited
        location = /shorten {
            limit_req zone=shorten_limit burst=20 nodelay;

            proxy_pass http://app;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Переадресация и статистика
        location / {
            proxy_pass http://app;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
